# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 11:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('kind', models.CharField(max_length=11)),
                ('priority', models.CharField(max_length=8)),
                ('status', models.TextField(default='New')),
                ('votes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Usuaris',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('image_url', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='issues',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='asw_api.Usuaris'),
        ),
        migrations.AddField(
            model_name='comments',
            name='issue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='asw_api.Issues'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asw_api.Usuaris'),
        ),
    ]
