# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 11:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asw_api', '0002_auto_20171127_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='votes',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
