# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 19:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asw_api', '0002_auto_20171129_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
