# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asw_api', '0004_auto_20171129_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='owner',
        ),
    ]
