# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asw_api', '0005_auto_20171130_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datafile', models.FileField(upload_to=b'')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asw_api.Issues')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
