# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asw_api', '0007_auto_20171208_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issues',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2011-09-01T13:20:30+03:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issues',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.TextField(blank=True),
        ),
    ]
