# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asw_api', '0007_auto_20171207_1904'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUploads',
            new_name='Attachment',
        ),
    ]
