# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asw_api', '0009_remove_issues_votes'),
        ('asw_api', '0010_merge_20171210_1718'),
    ]

    operations = [
    ]
