# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asw_api', '0012_auto_20171218_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
